### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by cforce** [mexitek/redmine_wiki_html_util#4]
Do in undertsand correctly that this plugin offers all ways to cross site scripting?

**Comment by mexitek** [comment]
Yes I do. Like I said my blog post, this would be most useful for HTML/CSS UI demos. You don't want this plugin on a redmine wiki where everyone has edit access.

You definitely need to have limited permissions to edit the redmine wikis.

**Comment by robspearman** [comment]
How hard would it be to limit the macros to only work on locked wiki pages?

**Comment by mexitek** [comment]
I don't think it should be terribly difficult. I am sure that the macro has property information about the wiki page itself. Just a matter of digging around.

**Comment by robspearman** [comment]
I was able to figure this out (obj.page.protected is the key info required).  Would you want this to be the default behavior?  Can supply a patch if interested.

**Comment by mexitek** [comment]
Awesome! I think it would be ideal if there was a admin option that was not checked by default. (or atleast a config file)

So on locked pages, no one would be able to use the macros? Or only on locked pages?

**Comment by robspearman** [comment]
I set it up so the macros only work on locked pages.  That should limit any security issues to trusted users.

I'm actually having a hard time thinking of why anyone would not want this behavior.

**Comment by mexitek** [comment]
Our redmine server is for our software documentation. So all developers
should be able to put together a demo for their additions to our libraries.
Seeing that our server is in house it is not of concern. If we had a
network breach, the wiki was the least of our concerns.

It is good that you added it. I imagine for public redmine installs this is
crucial.

On Mon, Sep 10, 2012 at 5:06 PM, rkits notifications@github.com wrote:

> I set it up so the macros only work on locked pages. That should limit any
> security issues to trusted users.
> 
> I'm actually having a hard time thinking of why anyone would not want this
> behavior.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mexitek/redmine_wiki_html_util/issues/4#issuecomment-8438388.

## 

Arlo Carreon http://arlocarreon.com
Web Developer

**Comment by mexitek** [comment]
Feel free to to submit a pull request so i can integrate the changes
