### ISSUE TITLE
html edit and injection via wysiwhyg editor (tinymce)

### ISSUE THREAD

**Issue by cforce** [mexitek/redmine_wiki_html_util#5]
Wouldn't it be great if i can use a macro "{{tinymce}} to inject this editor  in a wiki site instead of raw html or css injection.
Then i can use this editor to produce the html code itself. The allowed html code  format which the editor can prodcude are configurable by admin via tinymce config gobally. It only prodcues valid html code!

The plugin must intercept wiki site show and wiki edit action if the wiki sites has macro {{tinymce}} 
If the site is hown the the tinymce content is passed through the mhl injection on the fly, if the site is in edit mode the tinymce editor is inject with the html which has been created for the tiny mce part before.

**Comment by cforce** [comment]
This approach allows section with plain old textile and/or sections with plain html created by tinmyce.

This is another approach compared to https://github.com/ebrahim/redmine_ckeditor which tries to do all with ckeditor (ckeidtor produces bad readable and buggy code) instead of being be able to only render parts iof the site (where textile hasn't the features to do so) with plain html created by a wysiwhyg editor

**Comment by mexitek** [comment]
Definitely sounds interesting, but I think this would be a whole separate plugin for redmine. Not part of this repo.
