### ISSUE TITLE
Wrong plugin identifier

### ISSUE THREAD

**Issue by bsl-zcs** [mexitek/redmine_wiki_html_util#7]
It shows as “redmine_gist” in the “Redmine plugins:” list at the redmine’s Administration/ Information page.

**Comment by mexitek** [comment]
What redmine version are you use?

**Comment by bsl-zcs** [comment]
I’m using Redmine 2.3.0.stable with skurfuerst’s fork of this plugin.

**Comment by mexitek** [comment]
![screen shot 2014-03-03 at 1 24 51 am](https://f.cloud.github.com/assets/515706/2307958/b27292c4-a2b5-11e3-91fa-de3ed1c4c343.png)

I see it show up correctly in 2.4

**Comment by bsl-zcs** [comment]
![image](https://f.cloud.github.com/assets/3049410/2311310/268e6de8-a2ef-11e3-98da-8e32deb81072.png)
Not being a rubyist myself, I guess it has been set here: https://github.com/mexitek/redmine_wiki_html_util/blob/master/init.rb#L7
That probably causes conflicts with the original gist plugin too.

**Comment by mexitek** [comment]
That makes sense! I'll change it later today.

On Monday, March 3, 2014, bsl-zcs notifications@github.com wrote:

> [image: image]https://f.cloud.github.com/assets/3049410/2311310/268e6de8-a2ef-11e3-98da-8e32deb81072.png
> Not being a rubyist myself, I guess it has been set here:
> https://github.com/mexitek/redmine_wiki_html_util/blob/master/init.rb#L7
> That probably causes conflicts with the original gist plugin too.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mexitek/redmine_wiki_html_util/issues/7#issuecomment-36536440
> .

## 

Arlo Carreon http://arlocarreon.com
Web Developer

**Comment by mexitek** [comment]
Updated the plugin identifier. Pull in the new changes
